volumes:
  mysql_volume:
  pgvolume:
  redis_data:

services:
  frankenphp:
    image: frankenphp-custom-with-extensions
    volumes:
      - ./laravel:/app
      - ./symfony:/symfony
    working_dir: /app
    user: www-data
    links:
      - pgsql
      - mysql
      - redis
    environment:
      - "APP_RUNTIME=Runtime\\FrankenPhpSymfony\\Runtime"
    entrypoint: ['tail', '-f', '/dev/null']
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306"
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: sandbox
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5432"
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379"
