volumes:
  mysql_volume:
  pgvolume:
  redis_data:

services:
  frankenphp:
    build:
      context: .
      dockerfile: frankenphp.Dockerfile
    volumes:
      - ./laravel:/app
    working_dir: /app
    user: www-data
    links:
      - pgsql
      - mysql
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "CADDYFILE=/app/Caddyfile"
      - "ASSET_HOST=http://localhost:8790"
    entrypoint: ['tail', '-f', '/dev/null']
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306"
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
      PGPASSWORD: secret
      POSTGRES_USER: user
      POSTGRES_DB: sandbox
    volumes:
      - pgvolume:/var/lib/postgresql/data
    ports:
      - "5432"
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379"
