#!/bin/bash

# let the user choose the Caddyfile before the test
read -p "Which Caddyfile? [worker.Caddyfile]: " caddyfile
caddyfile=${caddyfile:-worker.Caddyfile}
cp "$caddyfile" ./laravel/Caddyfile

# start in case we're not running
docker compose up -d

# reset databases and logs
docker compose exec frankenphp php artisan migrate:fresh --database=sqlite
docker compose exec frankenphp php artisan migrate:fresh --database=mysql
docker compose exec frankenphp php artisan migrate:fresh --database=pgsql
docker compose exec frankenphp rm storage/logs/*.log

# start the server
docker compose exec frankenphp sh test

# shut down
docker compose stop