#!/bin/bash

# set up the docker environment
docker compose build
docker compose up -d
docker compose exec frankenphp composer update
docker compose exec frankenphp php artisan octane:install --server=frankenphp

# migrate databases
docker compose exec frankenphp php artisan migrate:fresh --database=sqlite
docker compose exec frankenphp php artisan migrate:fresh --database=mysql
docker compose exec frankenphp php artisan migrate:fresh --database=pgsql

# start the server
docker compose exec -d frankenphp frankenphp run -c /app/resources/nonworker.Caddyfile

# run the tests
docker compose exec frankenphp php artisan test -p