#!/bin/bash

# let the user choose the Caddyfile before the test
read -p "Which Caddyfile? [Caddyfile]: " caddyfile
caddyfile=${caddyfile:-Caddyfile}
cp "$caddyfile" ./laravel/Caddyfile

# start in case we're not running
docker compose up -d

# reset databases
docker compose exec frankenphp php artisan migrate:fresh --database=sqlite
docker compose exec frankenphp php artisan migrate:fresh --database=mysql
docker compose exec frankenphp php artisan migrate:fresh --database=pgsql

# start the server
docker compose exec frankenphp frankenphp start -c /app/Caddyfile

# run the tests
docker compose exec frankenphp php artisan test -p

# shut down
docker compose stop